### ISSUE TITLE
ISSUE: POST Add booking plan without ranger should return 400 Bad Request

### ISSUE THREAD

**Issue by a-febri** [GunTour/Back-End#82]
### Steps to reproduce issue
1. Set Method to POST
2. Set auth `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHBpcmVkIjoxNjY3ODI5NDE2LCJpZCI6MTIsInJvbGUiOiJwZW5kYWtpIn0.XHn21oTUxIaseoVUvzpvmoXmOUcFGmAgAkZHB86jBws`
3. Set URL is https://mdanys.online/booking
4. Set body request:
```
{
  "date_start": "2023-02-19",
  "date_end": "2023-02-21",
  "entrance": "Pintu Masuk Cibodas",
  "ticket": 3,
  "product": [
    {
      "id_product": 1,
      "product_name": "Tenda",
      "product_qty": 3,
      "rent_price": 100000
    },
    {
      "id_product": 2,
      "product_name": "selimut",
      "product_qty": 3,
      "rent_price": 100000
    }
  ],
  "gross_amount": 200000
}
```

### Expected Result:

> Should return 400 Bad Request. (To create booking plan, ranger should be input)

### But, Actual result:

> API return 201 Created and and response body message "success add booking plan"

Lampiran

![Image](https://user-images.githubusercontent.com/109534135/200503016-0c3edf3d-6589-4a6a-b415-0bb671c6b5d4.png)

**Comment by khalidrianda** [comment]
ranger sama product optional, boleh kosong
